### ISSUE TITLE
"latest" tag points to 1.24 instead of 1.26

### ISSUE THREAD

**Issue by barnabasbusa** [deasmi/unraid-tailscale#13]
On dockerhub, the latest tag points to f58a2df58ee8 (1.24) not to d5e42c4cefae (1.26). 
Latest tag should be automatically created. There might be some bug in the pipeline for releases.

**Comment by deasmi** [comment]
This is deliberate. I will not move latest on .0 releases for at least a week as there are normally .1/2 releases soon afterward with bug fixes
