### ISSUE TITLE
SSH into Tailscale IP brings me to the Alpine Linux command line instead of Unraid

### ISSUE THREAD

**Issue by roughwood** [deasmi/unraid-tailscale#14]
I can access the Unraid web ui through the browser, but SSH always takes me to Alpine Linux. Container is running with all the default settings.

**Comment by eldudemeister** [comment]
Yes, same here. Just commenting so I can see any replies.

**Comment by deasmi** [comment]
@roughwood When you say ssh, what address are you using?

Works find for me 
`ssh root@<tailscale ip address for unraid>`

Also, if I go into the container, it isn't running ssh, so I have no idea where you are ending up but it isn't the tailscale container.

```
/app # ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 {docker-entrypoi} /bin/ash /app/docker-entrypoint.sh
    7 root      0:01 /app/tailscaled --state=/state/tailscaled.state --statedir=/state/
   52 root      0:00 /app/tailscale file get -wait=true -conflict=rename -loop=true /downloads
   53 root      0:00 sleep infinity
   67 root      0:00 /bin/sh
   73 root      0:00 ps -ef
/app #
```

**Comment by deasmi** [comment]
@roughwood try doing a ps -ef in the alpine you end up in, see if you can work out where you are.

**Comment by eldudemeister** [comment]
Mine works as you suggest, I was more trying to make use of the new tailscale ssh feature so I had passed the ssh flag and when I did that it would take me straight into the alpine container rather than the host

**Comment by deasmi** [comment]
Then I think that's working as advertised to be honest.

**Comment by deasmi** [comment]
@eldudemeister if you are enabling the ssh support in tailscale then this is expected behaviour, closing.
