### ISSUE TITLE
Regular releases?

### ISSUE THREAD

**Issue by aaomidi** [deasmi/unraid-tailscale#15]
Could we setup regular docker builds of this to keep up with latest images?

**Comment by k10urzd** [comment]
Yes please! Maybe there is a way to reference the Tailscale repo? My docker is on 1.28 but the Linux version is on 1.30

**Comment by aaomidi** [comment]
I'll make a PR/Fork

**Comment by ollysharp** [comment]
any luck with this?

**Comment by deasmi** [comment]
I am not going to do that, as I've explained in forums many times. 

x.0 releases are often buggy and an x.1 comes out soon after, so wouldn't be inflicting those on user base.
I normally wait at least 2 weeks after a x.1 release before I push a new version to avoid issues for people.

If you want to make your own docker however no need to fork, this is just a build script, you can build any version with it and use that if you wish.

./build.sh <version> (<dev>) 

dev at the end will tage the image with dev

**Comment by deasmi** [comment]
I will have a look at automatially pushing builds, but latest tag is never going to auto update

**Comment by deasmi** [comment]
I will have a look at automatially pushing builds, but latest tag is never going to auto update

**Comment by deasmi** [comment]
Not sure how this could be done easily however. 

https://stackoverflow.com/questions/58465057/trigger-a-github-action-when-another-repository-creates-a-new-release

If you can think of a way I would be happy to accept a PR with the guthub actions in it, otherwise it's still me doing it manually I'm afraid.

**Comment by k10urzd** [comment]
Hey @deasmi , any chance you can upgrade to 1.32.3 which addresses some serious vulnerabilities? Or provide more information on how we can manually upgrade?

**Comment by aaomidi** [comment]
My needs with tailscale grew a bit separate from this project (needed to be able to specify flags), so I've made this alternative: https://github.com/aaomidi/tailscale-sidecar

I'll try to get a PR working for this repo as well.

**Comment by deasmi** [comment]
Closing this as not an open issue
