### ISSUE TITLE
Is there a way to get a https cert?

### ISSUE THREAD

**Issue by UberMetroid** [deasmi/unraid-tailscale#16]
Is there a way to get a https cert?

Looking for help here. I am trying to provision a tailscale cert for my unraid set up. What do I need to type in the terminal to get a cert?
tailscale cert
tailscale
cert
are all not working. I feel like I am missing something here.

**Comment by deasmi** [comment]
You would only be able to do this in the console of the container, not the unraid console. 

Docker tab, click on tailscale, console

**Comment by UberMetroid** [comment]
Sorry - reopening this if possible. I need help with this. I go to the console for the container and I type it "tailscale cert" with out the quotes, but all I get is "sh: tailscale: not found". 
Ideas?

**Comment by JeremiePlam** [comment]
> Sorry - reopening this if possible. I need help with this. I go to the console for the container and I type it "tailscale cert" with out the quotes, but all I get is "sh: tailscale: not found". Ideas?

`./tailscale cert machine.tailnet` in the docker console

_machine_ is your machine name, which by default is _unraid_ if you haven't renamed it
_tailnet_ is your tailnet name which generally ends with _*.ts.net_

If you use the command `./tailscale cert` alone, it should automatically tell you the proper values to put in
