### ISSUE TITLE
Potentially update to 1.36 to get access to the update command

### ISSUE THREAD

**Issue by penz6** [deasmi/unraid-tailscale#19]
Hello all! I was browsing the tailscale changelog and realized that they added a command to update the client from the terminal. I was hoping that this could fix the issue of updating the container manually by the maintainers constantly. Not sure if it would work with the container and the way it works, pretty clueless about the way that docker works.

**Comment by deasmi** [comment]
I don't think this is an issue to solve.

The value I am trying to provide with Tailscale for unraid is a guaranteed working version, this would remove any testing and likely lead to issues.  Or at least changes are documented before being pushed as latest tag to people.

Also, it wouldn't work well in docker really, as the container is ephemeral, so it would have to update every time it started, making the user experience somewhat poor.
