### ISSUE TITLE
Exit node setup

### ISSUE THREAD

**Issue by CorruptComputer** [deasmi/unraid-tailscale#20]
I am not able to access other devices on my home network using my Unraid server as an exit node. I have everything configured for this to be possible, but I think that the container is missing the sysctl config they give in the documentation here: https://tailscale.com/kb/1103/exit-nodes/#enable-ip-forwarding

**Comment by deasmi** [comment]
This is unsupported I am afraid. 

Please see forums.

**Comment by CorruptComputer** [comment]
What support forums? I don't see any link in the repo to a forum.

**Comment by deasmi** [comment]
> What support forums? I don't see any link in the repo to a forum.

Apologies, hadn't merged docs with the link. 

https://forums.unraid.net/topic/90719-support-tailscale-support-thread/
