### ISSUE TITLE
Add a DAEMON_FLAGS env

### ISSUE THREAD

**Issue by jthoward64** [deasmi/unraid-tailscale#24]
It would be nice to be able to pass flags to `tailescaled` as well as `tailscale up`

**Comment by deasmi** [comment]
Please see Closed #23 

What is the use case here?

**Comment by jthoward64** [comment]
> Please see Closed #23
> 
> What is the use case here?

setting `--tun=userspace-networking`, `--debug=localhost:8080`, or `--port=N` mainly
