### ISSUE TITLE
Update Version

### ISSUE THREAD

**Issue by maxexcloo** [deasmi/unraid-tailscale#7]
Hi,

I'm pulling this package using Docker and all is working - however the Tailscale admin panel is saying the version is out of date.

I can see the VERSION arg but I can't see where it's set, both here or in the CA template...

Any chance you can help with this?

**Comment by deasmi** [comment]
@maxexcloo I'm not sure I can see this problem.

Current version is 1.16.2 and that is what is showing in my tailscale admin interface. 

Are you perhaps not running :latest tag and have a specific version downloaded?
