### ISSUE TITLE
Automatically download files from Taildrop

### ISSUE THREAD

**Issue by deasmi** [deasmi/unraid-tailscale#8]
Add a setting to automatically download files from Taildrop to a configured local location.

**Comment by deasmi** [comment]
This is currently thought to be impossible due to underlying Tailscale linux lack of support.

Tracking this for change to that.

https://github.com/tailscale/tailscale/issues/2312

**Comment by hugochinchilla** [comment]
On April 22, Tailscale v1.24.0 was released introducing support for `file get --loop` and `file get --conflict=(skip|overwrite|rename)`

**Comment by deasmi** [comment]
Thanks @hugochinchilla for spotting. I will do some initial testing and see what the best way to incorporate this is. Then likely do a special release for testing.

**Comment by deasmi** [comment]
@hugochinchilla I have got this working but would apprecaite some additional testing, would you be willing to give it a try as well?

**Comment by hugochinchilla** [comment]
Yes, I'm on a travel now, but I will test it on arrival.

**Comment by deasmi** [comment]
@hugochinchilla you will need to add a new path and a variable, as shown.

![image](https://user-images.githubusercontent.com/77708/168469005-018339de-66cf-41da-88d5-2caf19f089a7.png)

make /downloads point to where you'd like the uploaded files to be put.

Then set a variable ENABLE_DOWNLOADS to TRUE

change your docker tag to be deasmi/unraid-tailscale:downloads to pull the beta

Thanks

**Comment by hugochinchilla** [comment]
I've enabled it and it looks like is working fine. I will keep it running more time and test again later.

**Comment by deasmi** [comment]
I'm going to close this and update the latest tag, if you have seen no issues and neither have I that's loads more testing than I'd usually do ! Thanks @hugochinchilla
