### ISSUE TITLE
Update image to 1.20.4?

### ISSUE THREAD

**Issue by karan** [deasmi/unraid-tailscale#9]
It fixes a DNS issue that would be good to bring in.

**Comment by pugson** [comment]
The latest is 1.22.0 now.

**Comment by deasmi** [comment]
dev-1.20.4 tag is now available, I will test and update latest in coming days,

**Comment by deasmi** [comment]
dev-1.22.0 tag also available, this likely won't make it to latest as normally they release an version very soon after a .0 release.

**Comment by deasmi** [comment]
1.22.2 is now available and latest is point at that.
